1.21 added descriptions of Story.write*() samples to recipes.
pymupdf/PyMuPDF pull request #2003
Opened 2022-10-28 15:59 UTC by julian-smith-artifex-com

2022-10-28 16:04 UTC, JorjMcKie approved these changes

2022-10-31 15:44 UTC, jamie-lemon requested changes

2022-10-31 16:13 UTC, julian-smith-artifex-com commented on docs/recipes-stories.rst
> +[The reasons for this are a little involved; for example a `DocumentWriter` is
Have updated to hopefully address these suggestions.

2022-10-31 16:25 UTC, jamie-lemon approved these changes

2022-10-31 16:25 UTC, merged