1.21
pymupdf/PyMuPDF pull request #2041
Opened 2022-11-11 18:54 UTC by julian-smith-artifex-com

Various minor fixes.

2022-11-11 18:59 UTC, JorjMcKie approved these changes

2022-11-14 12:10 UTC, jamie-lemon commented on docs/installation.rst
> +    environmental variable `PYMUPDF_SETUP_DEVENV` to the location of the
Hmmm,  it is a bit of a grey area, but double backpacks for anything `code related` would be my preference.

2022-11-14 12:14 UTC, jamie-lemon commented on docs/installation.rst
>    https://www.macports.org/install.php
See previous comment

2022-11-14 12:15 UTC, jamie-lemon commented on tests/README.md
> +pytest command line.
Double back ticks for all the code refs?

2022-11-14 12:17 UTC, jamie-lemon requested changes
Just a few ideas to tidy things up if possible.

2022-11-14 15:30 UTC, jamie-lemon approved these changes

2022-11-14 15:46 UTC, merged