Fix typos
pymupdf/PyMuPDF pull request #2315
Opened 2023-03-31 01:29 UTC by kianmeng

Found via `codespell docs -L ist`

2023-03-31 08:37 UTC, jamie-lemon commented
Thanks for this, could you possibly redo this and target the 1.21 branch? ( Or documentation on master is a little out of date )

2023-04-01 04:27 UTC, kianmeng commented
@jamie-lemon Done. Please check.

2023-04-03 07:45 UTC, jamie-lemon requested changes
Thank you. One small change required.

2023-04-03 07:45 UTC, jamie-lemon commented on docs/recipes-general.rst
> +With the command line utility *pdftk* (`available <https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/>`_ for Windows only, but reported to also run under `Wine <https://www.winehq.org/>`_) a simila
I think this diff is incorrect - `overthere` is part of a URL.

2023-04-04 13:37 UTC, julian-smith-artifex-com commented
recheck

2023-04-04 13:42 UTC, julian-smith-artifex-com commented
> Found via `codespell docs -L ist`
> 
> I have read the CLA Document and I hereby sign the CLA

It looks like the automated CLA system isn't recognising this as acceptance of the CLA.

I think it might be because of the other text in your message "Found via `codespell docs -L ist`".

Could you try again, this time posting just the acceptance text in a message here?

2023-04-05 05:20 UTC, kianmeng commented
@julian-smith-artifex-com I've updated the PR comment to only CLA agreement line. Please check again.

2023-04-05 08:29 UTC, julian-smith-artifex-com commented
> @julian-smith-artifex-com I've updated the PR comment to only CLA agreement line. Please check again.

Unfortunately that doesn't seem to have worked. Could you try  creating a new message with the CLA text?

2023-04-06 02:38 UTC, kianmeng commented
I have read the CLA Document and I hereby sign the CLA

2023-04-06 07:45 UTC, julian-smith-artifex-com commented
recheck

2023-04-06 08:05 UTC, jamie-lemon approved these changes

2023-04-06 08:05 UTC, jamie-lemon commented
recheck

2023-04-06 08:08 UTC, merged