Fixing #2427
pymupdf/PyMuPDF pull request #2443
Opened 2023-06-01 17:34 UTC by JorjMcKie

Change the wording to correctly reflect the picture.

2023-06-01 22:23 UTC, jamie-lemon commented
Looking at the bug and the picture there isn't the final rotation 30 degrees clockwise ( not anti-clockwise ) ?

2023-06-01 22:31 UTC, jamie-lemon requested changes

2023-06-02 05:29 UTC, JorjMcKie commented on docs/matrix.rst
> -Finally a rotation by 30 clockwise degrees (*prerotate(-30)*).
Hm - to be honest: that matrix is anti-clockwise was - a long time ago - simply copied from MuPDF description.

2023-06-02 10:00 UTC, jamie-lemon commented on docs/matrix.rst
> -Finally a rotation by 30 clockwise degrees (*prerotate(-30)*).
I'm confused - it looks like the image is rotated clockwise?

2023-06-15 14:42 UTC, JorjMcKie commented on docs/matrix.rst
> -Finally a rotation by 30 clockwise degrees (*prerotate(-30)*).
I have uploaded a revised version. This applies to text in the .rt file as well as replacing the images involved in visualizing matrix effects.

2023-06-15 15:24 UTC, jamie-lemon commented on docs/matrix.rst
> +:attr:`Matrix.is_rectilinear`     true if rect corners will remain rect corners
Loads more clear with those new images.

2023-06-15 16:37 UTC, jamie-lemon approved these changes
LGTM

2023-06-15 19:50 UTC, merged